# Do not build on tags (GitHub and BitBucket)
skip_tags: true

branches:
  only:
  - master
  - dev

environment:
  matrix:
  - PYTHON: "C:\\Python37"
    PYTHON_VERSION: "3.7.x"
    PYTHON_ARCH: "32"
init:
- "SET PATH=%PYTHON%;%PATH%"

- python -V
- python -m pip install --upgrade pip
- python -m pip install --upgrade setuptools wheel virtualenv

before_build:
- python -m virtualenv venv
- venv\Scripts\activate
- python -c "import sys; print(sys.executable)"
- pip install -r requirements.txt
- pip install -r requirements_dev.txt

build_script:
- python -c "print('dummy build stage to disable MSBuild')"

test_script:
- python -m pytest

artifacts:
- path: 'dist/*.exe'
- path: 'build/coverage/html/*'

deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  description: Build v$(appveyor_build_version)
  auth_token:
    secure: aEuceXtTw4tyxWydRznIxKqzxFIkZAFriOlmvvjYFsmP57I/0uWNWCZc2GcRylOa
  artifact: dist/StarboundMapViewer.exe
  draft: false
  on:
    branch: master
    appveyor_repo_tag: false

before_deploy:
- pip install pyinstaller
- pyinstaller mapviewer.spec
